trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*
  paths:
    include:
    - '*'
    exclude:
    - README.md
    - docs/*
    # not trigger onnx2bnn build when only dabnn is edited
    - dabnn/*
pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - README.md
    - docs/*
    # not trigger onnx2bnn build when only dabnn is edited
    - dabnn/*

jobs:
- job: LinuxAppImage
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    submodules: true
  - script: sudo apt install -y protobuf-compiler libprotobuf-dev
    displayName: Install protobuf
  - bash: ci/build_onnx2bnn.sh
    displayName: Build
  - bash: ci/build_appimage.sh
    displayName: Build AppImage
  - task: CopyFiles@2
    inputs:
        contents: 'onnx2bnn.AppImage'
        targetFolder: $(Build.ArtifactStagingDirectory)
  - template: template_onnx2bnn_publish_artifacts.yml
  - template: template_onnx2bnn_github_release.yml
- job: Windows
  pool:
      vmImage: 'vs2017-win2016'
  steps:
  - checkout: self
    submodules: true
  - bash: ci/build_onnx2bnn.sh
    displayName: Build
  - template: template_onnx2bnn_publish_artifacts.yml
  - template: template_onnx2bnn_github_release.yml
- job: macOS
  pool:
      vmImage: 'macOS-10.14'
  steps:
  - checkout: self
    submodules: true
  - bash: ci/build_onnx2bnn.sh
    displayName: Build
  - script: 'cp build_onnx2bnn/tools/onnx2bnn/onnx2bnn build_onnx2bnn/tools/onnx2bnn/onnx2bnn-macos'
    displayName: 'Rename onnx2bnn'
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'build_onnx2bnn/tools/onnx2bnn'
      contents: 'onnx2bnn-macos'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - template: template_onnx2bnn_publish_artifacts.yml
  - template: template_onnx2bnn_github_release.yml
